// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtZreBHRztWyqKErjS0YIgLA1gfCP9LE',
    appId: '1:299499126037:web:1c43460a653bf33555bd1c',
    messagingSenderId: '299499126037',
    projectId: 'secgec-b990e',
    authDomain: 'secgec-b990e.firebaseapp.com',
    storageBucket: 'secgec-b990e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHNvoShjr5V4bwewzg17hhLyv1zDx-R-o',
    appId: '1:299499126037:android:4ebebf96a3dddaa055bd1c',
    messagingSenderId: '299499126037',
    projectId: 'secgec-b990e',
    storageBucket: 'secgec-b990e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_KhsA77B-juA5fjyhVeKre2hbTH_2C04',
    appId: '1:299499126037:ios:0eaa2b55d1520a8955bd1c',
    messagingSenderId: '299499126037',
    projectId: 'secgec-b990e',
    storageBucket: 'secgec-b990e.firebasestorage.app',
    iosClientId: '299499126037-oo14o6ge7bkohed4lpmejv5m0j98m9h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.secgec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_KhsA77B-juA5fjyhVeKre2hbTH_2C04',
    appId: '1:299499126037:ios:0eaa2b55d1520a8955bd1c',
    messagingSenderId: '299499126037',
    projectId: 'secgec-b990e',
    storageBucket: 'secgec-b990e.firebasestorage.app',
    iosClientId: '299499126037-oo14o6ge7bkohed4lpmejv5m0j98m9h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.secgec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADtZreBHRztWyqKErjS0YIgLA1gfCP9LE',
    appId: '1:299499126037:web:39b53cddac35cb2555bd1c',
    messagingSenderId: '299499126037',
    projectId: 'secgec-b990e',
    authDomain: 'secgec-b990e.firebaseapp.com',
    storageBucket: 'secgec-b990e.firebasestorage.app',
    measurementId: 'G-4C6R0HE527',
  );

}